Failure # 1 (occurred at 2023-11-16_20-38-53)
The actor died because of an error raised in its creation task, [36mray::SAC.__init__()[39m (pid=38588, ip=127.0.0.1, actor_id=6f2ed79850b3be17cfed5c1301000000, repr=SAC)
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
             ^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=38596, ip=127.0.0.1, actor_id=7d44ea75cf3bb436ceee897101000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x127490850>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 525, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1727, in _update_policy_map
    self._build_policy_map(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1838, in _build_policy_map
    new_policy = create_policy_for_framework(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/utils/policy.py", line 141, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/policy/policy_template.py", line 260, in __init__
    validate_spaces(self, obs_space, action_space, self.config)
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/algorithms/sac/sac_tf_policy.py", line 762, in validate_spaces
    raise UnsupportedSpaceException(
ray.rllib.utils.error.UnsupportedSpaceException: Action space (Dict('accept': Discrete(4), 'invite': Discrete(2))) of SACTorchPolicy is not supported for SAC. Must be [Box|Discrete|Simplex].

During handling of the above exception, another exception occurred:

[36mray::SAC.__init__()[39m (pid=38588, ip=127.0.0.1, actor_id=6f2ed79850b3be17cfed5c1301000000, repr=SAC)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/algorithms/sac/sac.py", line 354, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/utils/deprecation.py", line 106, in patched_init
    return obj_init(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 517, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/algorithms/algorithm.py", line 639, in setup
    self.workers = WorkerSet(
                   ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/ray/rllib/evaluation/worker_set.py", line 179, in __init__
    raise e.args[0].args[2]
ray.rllib.utils.error.UnsupportedSpaceException: Action space (Dict('accept': Discrete(4), 'invite': Discrete(2))) of SACTorchPolicy is not supported for SAC. Must be [Box|Discrete|Simplex].
