Failure # 1 (occurred at 2023-11-16_16-55-24)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=23353, ip=127.0.0.1, actor_id=d71e4fadf401f6b76604115b01000000, repr=PPO)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 227, in _setup
    self.add_workers(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 593, in add_workers
    raise result.get()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/utils/actor_manager.py", line 481, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=23365, ip=127.0.0.1, actor_id=a367b294533a629250c168b901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7f799116dfa0>)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 525, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1727, in _update_policy_map
    self._build_policy_map(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1838, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/utils/policy.py", line 141, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 49, in __init__
    TorchPolicyV2.__init__(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/policy/torch_policy_v2.py", line 92, in __init__
    model = self.make_rl_module()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/policy/policy.py", line 431, in make_rl_module
    marl_module = marl_spec.build()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/marl_module.py", line 462, in build
    module = self.marl_module_class(module_config)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/marl_module.py", line 58, in __init__
    super().__init__(config or MultiAgentRLModuleConfig())
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 369, in __init__
    self.setup()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/marl_module.py", line 65, in setup
    self._rl_modules[module_id] = module_spec.build()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 104, in build
    module = self.module_class(module_config)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 377, in new_init
    previous_init(self, *args, **kwargs)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/torch/torch_rl_module.py", line 82, in __init__
    RLModule.__init__(self, *args, **kwargs)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/rl_module/rl_module.py", line 369, in __init__
    self.setup()
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo_rl_module.py", line 24, in setup
    self.pi = catalog.build_pi_head(framework=self.framework)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/algorithms/ppo/ppo_catalog.py", line 140, in build_pi_head
    action_distribution_cls = self.get_action_dist_cls(framework=framework)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/models/catalog.py", line 217, in get_action_dist_cls
    return self._action_dist_class_fn(framework=framework)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/models/catalog.py", line 445, in _get_dist_cls_from_action_space
    partial_multi_action_distribution_cls = _multi_action_dist_partial_helper(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/models/catalog.py", line 570, in _multi_action_dist_partial_helper
    child_distribution_cls_struct = tree.map_structure(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/tree/__init__.py", line 435, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/tree/__init__.py", line 435, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/models/catalog.py", line 571, in <lambda>
    lambda s: catalog_cls._get_dist_cls_from_action_space(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/core/models/catalog.py", line 507, in _get_dist_cls_from_action_space
    raise NotImplementedError(f"Unsupported action space: `{action_space}`")
NotImplementedError: Unsupported action space: `MultiBinary(2)`

During handling of the above exception, another exception occurred:

[36mray::PPO.__init__()[39m (pid=23353, ip=127.0.0.1, actor_id=d71e4fadf401f6b76604115b01000000, repr=PPO)
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 517, in __init__
    super().__init__(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/algorithms/algorithm.py", line 639, in setup
    self.workers = WorkerSet(
  File "/Users/jang-yejun/opt/anaconda3/lib/python3.9/site-packages/ray/rllib/evaluation/worker_set.py", line 179, in __init__
    raise e.args[0].args[2]
NotImplementedError: Unsupported action space: `MultiBinary(2)`
